name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/prace.tex
      - name: Upload pdf as artifact	
        uses: actions/upload-artifact@v2	
        with:
          name: src/prace.pdf
          path: ./github_artifacts
